#!/bin/bash
function clr
{
	cd $1
	rm -f *.class
}




echo "start clear class file"
for file in /home/work/java_learn/*
do
	if [ -d "$file" ]
	then
		clr $file
	fi
done

echo "finish clear class file"
